#!/bin/sh
# Simple script to create custom initramfs, this script must be run inside the 
# working directory that contains the files to be included in the initramfs. 
# The Linux kernel expects a gzip'd cpio archive for an intramfs which is 
# precisely what we are creating from the contents of the working directory.  
# This script also attempts to mount you boot directory in order to place the 
# newly created initramfs in its correct place. 

NAME="custom_initramfs.igz"

fail(){
echo
echo Borked! either the cpio or gzip operation failed
exit
}
mount_fail(){
echo
echo Please manually mount your boot directory
exit
}

# Check for root permissions
if [ "$(id -u)" != "0" ]; then
    echo "You must have root permissions to run this script"
    exit 1
fi
echo creating cpio archive...
find . |cpio -H newc -o > /tmp/temp.cpio || fail
sleep 1
echo G-zipping it up...
if df | grep -q boot; 
then
  cat /tmp/temp.cpio | gzip > /boot/$NAME || permission_fail
else
  mount /boot || mount_fail
fi
cat /tmp/temp.cpio | gzip > /boot/$NAME || fail
echo cleaning up...
rm /tmp/temp.cpio
echo Finished! check your boot directory and remember to update your bootloader. 
