#!/bin/sh
#Run this inside the DIR that contains the file heirarchy
#that you want to put inside your initramfs.
#EXAMPLE # cd /path/to/files/ && create_initramfs

NAME="custom_initramfs.igz"

fail(){
echo
echo Borked! either the cpio or gzip operation failed
exit
}
mount_fail(){
echo
echo Please manually mount your boot directory
exit
}

# Check for root permissions
if [ "$(id -u)" != "0" ]; then
    echo "You must have root permissions to run this script"
    exit 1
fi
echo creating cpio archive...
find . |cpio -H newc -o > /tmp/temp.cpio || fail
sleep 1
echo G-zipping it up...
if df | grep -q boot; 
then
  cat /tmp/temp.cpio | gzip > /boot/$NAME || fail
else
  mount /boot || mount_fail
fi
cat /tmp/temp.cpio | gzip > /boot/$NAME || fail
echo cleaning up...
rm /tmp/temp.cpio
echo Finished! check your boot directory and remember to update your bootloader. 
