#!/bin/bash
# This script can be used to open any gzipped cpio archive which  
# is the format normally used to created an initramfs we accomplish 
# this by creating a working directory then unzipping and extracting 
# the archive into it so you can see or edit everything that goes 
# into your initramfs at boot.

DIR="extracted_initramfs"

fail() {
echo
echo Borked! did you remember to specify a file?
exit
}

# Check for root permissions
if [ "$(id -u)" != "0" ]; then
    echo "You must have root permissions to run this script" 
    exit 1
fi
echo Creating working directory ...
mkdir $DIR || fail 
cd $DIR 
echo Unzipping and decrompressing ...
cp "$1" zipped.cpio.gz || fail
gunzip zipped.cpio.gz  || exit
cpio -id < zipped.cpio 
rm zipped.cpio 
echo Success! 
echo
echo The directory extracted_initramfs should now contain the contents of the initramfs

